### PR TITLE
Update nokogiri to 1.6.8

### PR DESCRIPTION
**Pull request by monfresh**
**Why**: To address a security vulnerability

### CODE REVIEW

**Comment by md5** [comment]
@monfresh I haven't reviewed the licensing for Ohana, but you may be interested in this: https://github.com/sparklemotion/nokogiri/issues/1488

**Comment by monfresh** [comment]
Thanks. It seems like the license is a generic CfA license that was written at least 5 years ago and that many other CfA repos copy and paste. I wonder if it should be changed to something more standard.

**Comment by monfresh** [comment]
I'm not a license expert, so I don't really understand why this is an issue and why it's only being brought up now with nokogiri. There are probably 100 gems being installed by this app. I'm sure there are a variety of different licenses across the gems, and probably some LGPL ones in there. Why hasn't this been an issue before? Do people really check the license for each gem their app depends on?

**Comment by monfresh** [comment]
Out of curiosity, I started looking up the gems on rubygems.org, and pretty much all of them so far use the MIT license, except for `json`, which uses the [Ruby license](http://www.ruby-lang.org/en/about/license.txt).

**Comment by md5** [comment]
@monfresh I use [`license_finder`](https://github.com/pivotal/LicenseFinder) for this purpose. It makes whitelisting a list of licenses and having exceptions for specific gems really easy. It would be pretty easy to wire into the Travis CI to check PRs for new unapproved licenses.

In the case of Ohana, the LGPL thing doesn't matter, but I know many people developing software in corporate environments definitely have to check all their licenses (and anything with "GPL" in the name can raise a red flag in those environments, though LGPL is still sometimes allowed).

As for the Code For America license, it looks like a pretty straightforward 3-clause BSD-style license.

**Comment by md5** [comment]
And yes, I've found that most Ruby gems use MIT, BSD, Apache 2.0, or the Ruby license.

**Comment by md5** [comment]
Forgot to address this part:

> Thanks. It seems like the license is a generic CfA license that was written at least 5 years ago and that many other CfA repos copy and paste. I wonder if it should be changed to something more standard.

I think changing the license without having a CLA in place with all the contributors could be sticky business. Since the license appears to be a pretty standard BSD license, I don't see much need to change it.

I just did a quick check with `license_finder` and it looks like the only gems that might be incompatible with the license are `colorize` and `term-ansicolor`, which are both "GPL-2". Again, I'm not a lawyer, but I'm not sure whether a GPL gem can be incorporated into a BSD-licensed work.

Here's the report I got from `master`:

```console
$ license_finder 
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Dependencies that need approval:
actionmailer, 4.2.6, MIT
actionpack, 4.2.6, MIT
actionview, 4.2.6, MIT
activejob, 4.2.6, MIT
activesupport, 4.2.6, MIT
addressable, 2.3.8, "Apache 2.0"
ast, 2.3.0, MIT
benchmark-ips, 2.5.0, MIT
better_errors, 2.1.1, MIT
builder, 3.2.2, MIT
bummr, 0.1.2, MIT
bundler, 1.12.5, MIT
capybara, 2.7.1, MIT
chunky_png, 1.3.5, MIT
cliver, 0.3.2, MIT
coderay, 1.1.1, MIT
colorize, 0.7.7, GPL-2
compass, 1.0.3, MIT
compass-core, 1.0.3, MIT
compass-import-once, 1.0.5, MIT
compass-rails, 3.0.2, MIT
coveralls, 0.8.13, MIT
crack, 0.4.3, MIT
dalli, 2.7.6, MIT
derailed, 0.1.0, MIT
derailed_benchmarks, 1.3.0, MIT
diff-lcs, 1.2.5, "MIT, Perl Artistic v2, GNU GPL v2"
docile, 1.1.5, MIT
email_spec, 2.1.0, MIT
erubis, 2.7.0, MIT
execjs, 2.6.0, MIT
faraday, 0.9.2, MIT
faraday-http-cache, 1.3.0, "Apache 2.0"
ffi, 1.9.10, BSD
figaro, 1.1.1, MIT
flamegraph, 0.9.5, MIT
font-awesome-rails, 4.6.3.0, "MIT, SIL Open Font License"
get_process_mem, 0.2.0, MIT
globalid, 0.3.6, MIT
google-api-client, 0.9.9, "Apache 2.0"
googleauth, 0.5.1, "Apache 2.0"
haml, 4.0.7, MIT
haml-rails, 0.9.0, MIT
haml_lint, 0.17.1, MIT
hashdiff, 0.3.0, MIT
heapy, 0.1.2, MIT
hike, 1.2.3, MIT
html2haml, 2.0.0, MIT
htmlentities, 4.3.4, MIT
httpclient, 2.8.0, ruby
hurley, 0.2, MIT
i18n, 0.7.0, MIT
json, 1.8.3, unknown
jwt, 1.5.4, MIT
kaminari, 0.17.0, MIT
kgio, 2.10.0, LGPL-2.1+
launchy, 2.4.3, ISC
letter_opener, 1.4.1, MIT
listen, 3.0.6, MIT
little-plugger, 1.1.4, MIT
logging, 2.1.0, MIT
loofah, 2.0.3, MIT
mail, 2.6.4, MIT
memcachier, 0.0.2, MIT
memoist, 0.14.0, MIT
memory_profiler, 0.9.6, MIT
mime-types, 3.1, MIT
mime-types-data, 3.2016.0521, MIT
mini_portile2, 2.1.0, MIT
minitest, 5.9.0, MIT
multi_json, 1.12.1, MIT
multipart-post, 2.0.0, MIT
nokogiri, 1.6.8, MIT
ohanakapa, 1.1.2, MIT
os, 0.9.6, MIT
parser, 2.3.1.2, MIT
pkg-config, 1.1.7, LGPLv2+
poltergeist, 1.9.0, MIT
powerpack, 0.1.1, MIT
puma, 3.4.0, "New BSD"
quiet_assets, 1.1.0, "MIT, GPL"
rack, 1.6.4, MIT
rack-cache, 1.6.1, MIT
rack-mini-profiler, 0.10.1, MIT
rack-rewrite, 1.5.1, MIT
rack-test, 0.6.3, MIT
rails-deprecated_sanitizer, 1.0.3, MIT
rails-dom-testing, 1.0.7, MIT
rails-html-sanitizer, 1.0.3, MIT
rails_12factor, 0.0.3, MIT
rails_serve_static_assets, 0.0.5, MIT
rails_stdout_logging, 0.0.4, MIT
railties, 4.2.6, MIT
rainbow, 2.1.0, MIT
rake, 10.5.0, MIT
rb-fsevent, 0.9.7, MIT
rb-inotify, 0.9.7, MIT
representable, 2.3.0, MIT
requirejs-rails, 0.9.5, MIT
retriable, 2.1.0, MIT
rspec-core, 3.4.4, MIT
rspec-expectations, 3.4.0, MIT
rspec-mocks, 3.4.1, MIT
rspec-rails, 3.4.2, MIT
rspec-support, 3.4.1, MIT
rubocop, 0.40.0, MIT
ruby-progressbar, 1.8.1, MIT
ruby_parser, 3.8.1, MIT
safe_yaml, 1.0.4, MIT
sass, 3.4.21, MIT
sass-rails, 5.0.4, MIT
sawyer, 0.5.5, MIT
sexp_processor, 4.7.0, MIT
signet, 0.7.3, "Apache 2.0"
simplecov, 0.11.2, MIT
simplecov-html, 0.10.0, MIT
spring, 1.7.1, MIT
spring-commands-rspec, 1.0.4, MIT
spring-watcher-listen, 2.0.0, MIT
sprockets, 2.12.4, MIT
sprockets-rails, 2.3.3, MIT
stackprof, 0.2.9, MIT
sysexits, 1.2.0, BSD
term-ansicolor, 1.3.2, GPL-2
thor, 0.19.1, MIT
thread_safe, 0.3.5, "Apache 2.0"
tilt, 1.4.1, MIT
tins, 1.6.0, MIT
tzinfo, 1.2.2, MIT
uber, 0.0.15, MIT
uglifier, 3.0.0, MIT
unicode-display_width, 1.0.5, MIT
vcr, 3.0.3, MIT
webmock, 2.1.0, MIT
websocket-driver, 0.6.3, MIT
websocket-extensions, 0.1.2, MIT
xpath, 2.0.0, unknown
yard, 0.8.7.6, MIT
```

**Comment by md5** [comment]
Out of curiousity, does @codeforamerica have any pro-bono legal resources available to review the licenses here?

**Comment by md5** [comment]
The last thing I'll mention is that the reason I brought it up for `nokogiri` is that I knew that moving from 1.6.7.x to 1.6.8 pulled in a LGPL dependency that wasn't there before. I hadn't examined the license situation with Ohana previously.

**Comment by monfresh** [comment]
Thanks! That's very helpful. Both of those GPL2 gems are not critical. `term-ansicolor` is used by coveralls, which we can remove by using Code Climate for test coverage, and `colorize` is used by `bummr`, which I can run locally since I'm pretty much the only one using it to update the gems.

**Pull request merged**
