### PR TITLE
Fixes #724 - removes extra space after comma

### LINKED ISSUE #724: Physical address has extra space before second comma
screen shot 2015-01-06 at 12 04 31 am

screen shot 2015-01-06 at 12 04 39 am

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes #724 - removes extra space after comma in physical address.

### CODE REVIEW

**Comment by anselmbradford** [comment]
@monfresh Ready for review and merge. If you know a way to do this in haml without the `&nbsp;` that would be more ideal.

**Comment by monfresh** [comment]
This was bug was introduced when you fixed haml-lint offenses in [this commit](https://github.com/codeforamerica/ohana-web-search/commit/911bff3f0926134c45d324becf865ee0fc68641d) :smile: 

The solution is to use string interpolation for the city comma:

```haml
%span{ itemscope: '', itemtype: 'http://schema.org/PostalAddress', itemprop: 'address' }
  %span.street-address{ itemprop: 'streetAddress' }><
    = superscript_ordinals(street_address_for(location.address))
  - if lines == 2
    %br
  - else
    ,

  %span.city{ itemprop: 'addressLocality' }
    #{location.address.city},

  %span.state{ itemprop: 'addressRegion' }
    = location.address.state

  %span.zipcode{ itemprop: 'postalCode' }
    = location.address.postal_code
```

**Comment by monfresh** [comment]
Also, could you please add a test for this, making sure that it fails first so we can catch this in the future.

**Comment by anselmbradford** [comment]
@monfresh Added an edit. How's it look? Thx!

**Comment by monfresh** [comment]
Looks good, mate!

**Pull request merged**
