### PR TITLE
Fixes 526 - adds tab index.

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes 526 - adds tab index to keyword, location, and agency input fields on the
inside search page and the keyword and search button on the homepage.

### CODE REVIEW

**Comment by anselmbradford** [comment]
@monfresh Do you see the problem with https://github.com/codeforamerica/ohana-web-search/commit/4a4fed945952a6aebd2096b73a34c2ee9da5588a ?

**Comment by monfresh** [comment]
@anselmbradford What problem are you referring to?

**Comment by anselmbradford** [comment]
Sorry for the brevity... let me explain. Do you ever add a test and run the suite and get totally unrelated failures? I once in awhile have and don't understand what's going on when it happens. Example: I added this tab-index test (`tab_index_spec.rb`), ran the test suite and for some reason some of the dynamic cassettes were re-generated with new cassettes, which obviously fail because the manually added variables weren't there. BUT, those cassettes have nothing to do with the `tab_index_spec.rb` file that I added that I can see. I threw out the replaced cassette changes and re-ran the test and other seemingly unrelated failures happened. The problem I was referring to was that I had [this](https://travis-ci.org/codeforamerica/ohana-web-search/builds/48219133) failure, for [this code](https://github.com/codeforamerica/ohana-web-search/commit/4a4fed945952a6aebd2096b73a34c2ee9da5588a), which is a `VCR::Errors::UnhandledHTTPRequestError`. However, in looking at the request URI and matching it to the requested URI in the cassette [here](https://github.com/codeforamerica/ohana-web-search/commit/4a4fed945952a6aebd2096b73a34c2ee9da5588a#diff-f73e07b19544e377c81ab95903578ec3R5), they match, so I'm unclear why this error happened. What I discovered though, was there actually was an error in the test that was throwing this error, in that the tab key was pressed once instead of twice ([here](https://github.com/codeforamerica/ohana-web-search/commit/4a4fed945952a6aebd2096b73a34c2ee9da5588a#diff-6568292f9fd4d8c20729dc93bd1fb40cR17)). I added the second tab key press and rebased this PR (and forgot to update my comment earlier—so that's why it was confusing), and then the tests passed. It seems like sometimes when adding tests there will be what appear to be random failures, which do indicate an error in the test but the actual error is not being shown—instead other parts of the suite fail.

Relatedly, is this the right approach for these tests? I'll add the rest if so.

**Comment by monfresh** [comment]
Here are a few observations I can make:

- VCR is not needed for these specs since no API calls are made or needed on the homepage. The fact that the cassette actually captured an API call and caused an error should have alerted you that something is wrong with the spec because it should just be tabbing to different elements, not submitting the form. Instead of questioning why VCR was complaining about a URL that was already captured in a cassette, I would have questioned why the spec was making an API call in the first place.

- To make sure a test is written properly, I would make sure the test fails first. For example, change the expectation in the `evaluate_script` line and make sure it fails. If it doesn't, then the spec is not testing what you want it to. For example, I set the last line in the first spec to `page.evaluate_script('document.activeElement.id') == 'foo'` and it passed, which is wrong. Remember, tests must always fail first. Red, green, refactor.

- From a cursory glance at the poltergeist documentation, sending a key to an element will act as if the user pressed that key *after* that element is already in focus. So, if you send a tab key to the keyword field on the homepage, it will simulate pressing the tab key *inside* the keyword field. This will then automatically set focus on the keyword field, and checking that the keyword is field is in focus at that point is not really testing that the tab index is set properly. I'm assuming what you're trying to test is that once the homepage is loaded, pressing the tab key once will place focus on the keyword field. For that, you would need to send the tab key to the `body` element. Then, you need to use Rspec's `expect` syntax, like this:
```ruby
expect(page.evaluate_script('document.activeElement.id')).to eq 'foo'
```

- Having said all of the above, I would actually just check the `tabindex

**Comment by monfresh** [comment]
Here's how I would rewrite those tests:

```ruby
feature 'tabindex for homepage elements' do
  before { visit '/' }

  it 'gives the keyword field a tabindex of 1' do
    expect(find('#keyword')[:tabindex]).to eq '1'
  end

  it 'gives the search button a tabindex of 2' do
    expect(find('#button-search')[:tabindex]).to eq '2'
  end
end
```

**Comment by anselmbradford** [comment]
Cool, thanks for the in-depth analysis. That makes sense. I'm still not clear why it went haywire, which made it difficult to know if the test was passing or failing to begin with. I'll try to document that further if it happens again. 

The only danger I can think of with only checking the tabindex value is that the tabindex could be set to 1 elsewhere earlier on the page and it wouldn't be detected by the test. The desired behavior of hitting tab on page load going to the keyword input would actually not happen if tabindex was set to 1 on an earlier element on the page, hence why I was trying to actually test a press of the tab key. But perhaps that's too granular for what is a minor feature. Or something like this could be done I think:

```ruby
...
it 'gives the keyword field a tabindex of 1' do
    expect(first('*[tabindex]')[:id]).to eq 'keyword'
    expect(find('#keyword')[:tabindex]).to eq '1'
end
...
```

**Comment by monfresh** [comment]
To test that there is only one element with a tabindex of 1 and only one with a tabindex of 2, I would write a separate test with this expectation:
```ruby
expect(all('*[tabindex]').map { |t| t[:tabindex] }).to eq %w(1 2)
```

**Comment by anselmbradford** [comment]
@monfresh Ready for review and merge. FYI I rebased prior edits into one commit.

**Comment by monfresh** [comment]
:+1:

**Pull request merged**
