### PR TITLE
Use git clone, not fork for local installation.

### PR DESCRIPTION
**Pull request by monfresh**
Forking is only for contributing back to this project. Everyone else should be cloning.

### CODE REVIEW

**Comment by anselmbradford** [comment]
:+1:

**Comment by md5** [comment]
This seems incompatible with `CUSTOMIZE.md` where you direct users to edit `config/locales/en.yml` for their installation.

**Comment by monfresh** [comment]
I don't understand how cloning makes the project any more or less compatible with customizations than forking. Both cloning and forking allow you to edit and version your files, and fetch changes from upstream if desired. If anything, cloning is better because when you push a PR to a fork, GitHub assumes that you want to send that PR to the upstream repo by default. So, if you are planning on sending PRs to your own version of the project a lot more often than to upstream, cloning is the way to go. If you plan on contributing back to the upstream repo, you can create a fork for that. That way, you separate the work for your custom version from the contribution work.

Also, we don't plan on modifying `en.yml` and `settings.yml` very often. Up until a minor change I made a few days ago, `settings.yml` had not been updated since October. The most recent changes to `en.yml` were to make it compatible with Ohana API, which was only just recently declared version 1.0. Before that, `en.yml` had not been changed since the end of November.

When you say "jump through hoops with Git", could you be more specific? Have you jumped through any of those hoops with this project?

If this project was a gem, and you made changes to your `settings.yml`, then updated to the latest version of the gem which contained changes to `settings.yml`, those latest changes would not automatically be incorporated into your version. If you wanted to pull those changes, you would have to visit this repo and see what the changes were, then manually copy and paste them into your custom file.
With Git, you would merge the upstream changes, and if there were conflicts, you would resolve them. Otherwise, you would be done.

**Comment by md5** [comment]
In `CONTRIBUTE.md`, it says this:

> Inside the config/locales folder, you will find a file called en.yml. In that file, you can customize much of the user-facing text on the website. Most of the text should be ready to go, but there is one specific setting you should customize: the location value under branding.

If I actually go and update `location` in `en.yml`, I need to commit it in order to push to Heroku. This immediately puts me in the position of having to deal with repeated git merges or rebases from upstream if I want to stay in sync. Those are the git hoops I'm referring to. No such merging or rebasing is necessary if all I need to do to update to the latest Ohana engine is to update my `Gemfile` to the latest version and run `bundle update`.

You're right that cloning v. forking doesn't make a difference here. What I meant is that it's misleading to make users think that they'll have a sane workflow if they simply work off a clone of `codeforamerica/ohana-web-search` without adding additional remotes. If they fork, their default `origin` will be something to which they can actually push the commits you're asking them to make.

In the case of the `settings.yml` for the gem/engine integration, I expect there would be an app-level `settings.yml` that would override the engine-level `settings.yml` (or something to that effect). In order to get the latest engine-level settings.yml changes, you'd update your `Gemfile` (or perhaps update the ref of a Git submodule pointing to an embedded `ohana-web-search-engine`).

**Comment by md5** [comment]
Also, I'm sorry if we've gotten off on the wrong foot @monfresh. I certainly don't want to come in and offer unsolicited opinions on your hard work. I'm just trying to figure out what the best way to work with the Ohana apps to support @hackforla.

**Comment by monfresh** [comment]
> Also, I'm sorry if we've gotten off on the wrong foot @monfresh.

No worries. I'm just trying to understand the situation and make sure to clear things up.

> it's misleading to make users think that they'll have a sane workflow if they simply work off a clone of codeforamerica/ohana-web-search without adding additional remotes.

We make no claims about workflow, so I don't see how this is misleading. We're also not mandating cloning over forking. Anyone is free to use the project however they choose. Based on my personal experience using a fork to build San Mateo County's custom version, I wish I had used a clone because of the additional step I have to go through every time I push a PR to the fork. The additional step is that I have to make sure I am sending the PR to my fork, and not the upstream repo. I've seen a lot of people get tripped up over this.

Based on the above, I think cloning offers an easier, less confusing, and less error-prone workflow, and the only other difference would be the additional setup of the GitHub repo + corresponding remote, which is a one-time operation that you can perform from the command line with the [hub CLI](https://github.com/github/hub#git-create) in a few seconds.

> If I actually go and update location in en.yml, I need to commit it in order to push to Heroku. This immediately puts me in the position of having to deal with repeated git merges or rebases from upstream if I want to stay in sync. 

You will have to commit your changes in order to push to Heroku regardless of whether or not the project is a gem. In order to get updates from upstream, the difference between regular repo and gem (in terms of the first step you need to perform) is running `git merge` vs `bundle update [gem]`.

> all I need to do to update to the latest Ohana engine is to update my Gemfile to the latest version and run bundle update

This is where I think there is confusion. As I mentioned in my previous comment:
> If this project was a gem, and you made changes to your settings.yml, then updated to the latest version of the gem which contained changes to settings.yml, those latest changes would not automatically be incorporated into your version. If you wanted to pull those changes, you would have to visit this repo and see what the changes were, then manually copy and paste them into your custom file.
With Git, you would merge the upstream changes, and if there were conflicts, you would resolve them. Otherwise, you would be done.

What I think this boils down to is whether you think that manually applying upstream changes is a better workflow than using Git. In other words, whether or not this project is a gem, you will still have to deal with conflict resolution. I'm not yet convinced that a gem offers a big enough workflow improvement to warrant the additional development and maintenance effort.

It would be helpful to know if you've actually already tried syncing with upstream and if you've run into any issues. If not, then until there is an actual problem with syncing, I think it's premature to discuss making big changes.

**Comment by md5** [comment]
I agree with you about the cloning in terms of easing in-project PR flow. It's definitely preferable for that reason. I also think you're right about the source of the confusion being a difference in understanding in how the gem/engine workflow would look.

I'm not at all suggesting applying changes from upstream manually. Any upstream changes to `settings.yml` or other files would be released in a new version of the gem and would be picked up by a `bundle update ohana-web-search-engine`. This is no different than using any other gem. My contention is that this is a lower bar to entry than having to deal with repeated git merges or rebases over time for more junior developers.

In my own personal case, I'm well able to deal with either workflow. I just think it raises the barrier to entry for localities creating and maintaining their own Ohana deployments since dealing with git conflicts generally takes a higher level of skill than dealing with Bundler updates.

I'm still curious whether @declan and @digitalWestie have actually deployed Ohana as an engine as @greggish suggested in #798. That might be a useful data point in terms of the actual level of effort involved in creating an maintaining the engine separate from the app.

**Comment by md5** [comment]
All that being said, this discussion probably belongs in #798.

**Comment by md5** [comment]
To get back on topic, how about adding this to the README after the `git clone` line:

```console
$ git remote set-url origin git@github.com:<your GitHub username>/ohana-web-search.git
```

**Comment by md5** [comment]
This would require creating the repo manually too, so it would be nice to mention that as well.

**Comment by md5** [comment]
Something like this could even be good:

```Markdown
Clone it on your computer and navigate to the project's directory:

    git clone git@github.com:codeforamerica/ohana-web-search.git
    cd ohana-web-search
    git remote rename origin upstream

Create a new repository on Github to hold your clone of `ohana-web-search`. This repository can be named whatever makes sense for your project (e.g. `mycity-ohana-web-search`). Then follow the instructions to add a new `origin` remote to your local repository:

    git remote add origin git@github.com:<GITHUB_USER>/<YOUR_REPO>.git
```

**Comment by monfresh** [comment]
That looks great. Wanna submit that in a PR?

I would also make sure `GitHub` is spelled correctly (capital H), and add a link to GitHub's tutorial on creating a repo: https://help.github.com/articles/create-a-repo/

**Comment by md5** [comment]
Sure. I'll submit a PR with a bit better wording once this merges. I'm planning to do some work on the @hackforla Ohana this week, so I'll do it then.

**Pull request merged**
