### PR TITLE
Add more guidance on how to manage Ohana git repos

### PR DESCRIPTION
**Pull request by md5**
I've updated the docs a bit as discussed in #801. I also threw in an update to refer to Ruby 2.2 instead of Ruby 2.1 due to the updates in 83d7f7625b8c6496d78a8d907240f5d60be41270

### CODE REVIEW

**Comment by md5** [comment]
The `git push` command should possibly be this instead:

    git push origin --mirror

**Comment by md5** [comment]
Let me know if this looks good or if you want anything changed. I'm willing to squash these commits too if you prefer that.

**Comment by monfresh** [comment]
The instructions look good as is (I wouldn't use the `--mirror` option), but I'm not sure they belong in the installation section because creating a GitHub repo is not required to be able to run the app locally. How you manage your repo after that is up to you, whether it's on GitHub, or just locally, or some other platform.

I think these instructions might better be placed at the end of `CUSTOMIZE.md` since it's at that point that you would be committing changes to your repo.

**Comment by md5** [comment]
I'm happy to update this PR to make it mergeable, but I'm not totally clear whether you want any changes to `INSTALL.md` or if you just want the additions made to `CUSTOMIZE.md`.

**Comment by monfresh** [comment]
I think your changes look great, but I think they fit better in `CUSTOMIZE.md` because those instructions aren't necessary during local installation. So, the first 2 diffs you made can stay in `INSTALL.md`, but the rest should go in `CUSTOMIZE.md`. Thanks!

**Comment by md5** [comment]
Updated. Let me know if this works.

**Comment by monfresh** [comment]
Looks good. One last thing I'll ask is to please squash into one commit. Thanks!

**Comment by md5** [comment]
Squashèd

**Comment by monfresh** [comment]
Olé!

**Pull request merged**
