### PR TITLE
Schema org fixes

### PR DESCRIPTION
**Pull request by md5**
Google's [structured data testing tool](https://developers.google.com/structured-data/testing-tool/) was returning a URL for the `name` property for the `/locations` URL on our Ohana Web Search instance. These changes should fix things.

### CODE REVIEW

**Comment by md5** [comment]
I'm actually thinking now that the `itemprop="url"` should be removed from the locations list view since it's pointing to an Ohana Web Search URI instead of a URI actually owned by the organization.

**Comment by monfresh** [comment]
@anselmbradford What do you think? You're more familiar with schema.org than I am.

**Comment by md5** [comment]
@anselmbradford @monfresh Any thoughts on this PR?

**Comment by anselmbradford** [comment]
Apologies for taking ages to reply! No structured data seems better than inaccurate structured data, so if itemprop="url" is pointing to the wrong thing I would err on the side of removing it.

**Comment by md5** [comment]
Updated to remove `itemprop="url"` from Ohana-internal links in the locations list view.

**Comment by md5** [comment]
:metal:

**Comment by anselmbradford** [comment]
Sorry it took forever.

**Comment by md5** [comment]
@anselmbradford no worries!

**Pull request merged**
