### PR TITLE
Fixes 526 - adds tab index helper.

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes 526 - adds tab index helper so that elements on the page can be
given an incrementing tab index.

### CODE REVIEW

**Comment by anselmbradford** [comment]
@monfresh I could use some help on this one. I want to have a helper that when called will increment a global tab index value, so that elements on the page can just reference the helper and end up with an incremented tab index that follows the rendering order of the page. That way we don't have to shuffle tabindex numbers between ohana web search and smc-connect, where the number of search filters differs. What I have sort of works, but it remembers the prior tab index value between refreshes of the page, which I don't want—I want it to start at 1 again on page reload. How would you do this in rails? (See addition to `ApplicationHelper`.) Thanks!

**Comment by monfresh** [comment]
This doesn't feel right to me. If this is specifically to address an issue with SMC-Connect, it does not belong in this repo. We should not be introducing code in this generic repo that won't be used by anyone except for SMC-Connect.

**Comment by anselmbradford** [comment]
What's the problem with this approach? It's not specific to smc-connect, but would make things easier there and for any forks where the input fields/buttons differ. Additionally, suppose down the road an input field from ohana web search is removed, or worse yet, one is added. With hardcoded tab indices this means that fields/buttons/etc subsequent to the one removed should be manually incremented or decremented. This feels like an area where one could easily be forgotten or the order could be mixed up. So what I was attempting here is to provide a helper method that just returns the next index available. If changes to a button/field happen, no other tab index update is needed and there is no need to figure out which partial comes before which.

How do you want to proceed on this issue?

**Comment by monfresh** [comment]
What is a tab index and why is it needed? From a user perspective, what is the problem that is being solved here?

**Comment by anselmbradford** [comment]
It sets the order of focus when clicking the tab key. So for example when clicking on the keyword search input field and typing a keyword, hitting the tab key may be expected to jump the focus to the location input field below, however it doesn't right away. Tab indices can be used in this case to tell the browser which elements on the page have focus priority over others. You can see it in use on yelp where the keyword input, location input, and search button have the tab indices 1, 2, and 3 respectively.

**Comment by monfresh** [comment]
Can you use JS for this?

http://stackoverflow.com/questions/15123054/adding-tabindex-dynamically

**Comment by anselmbradford** [comment]
I wouldn't recommend it. They're not dynamic values, so they should be set on the server. Crawling the DOM is an expensive operation, there will be a moment at page load where the tab indices aren't applied, etc. Just not ideal nor the right place for these values.

**Comment by monfresh** [comment]
I don't think using a helper with auto increment is the right approach because it's not clear what the value actually is when looking at the partial code, and I don't think it's guaranteed that the order will be the same every time.

Since the tab index values are meant to be static based on the existing set of input fields, then each field should be assigned a specific index. I would recommend storing this in an environment variable for each field. If you change the number of fields or the order of the fields, you'll have to update the env vars, so that everything remains explicit.

**Comment by anselmbradford** [comment]
Well, if the render order can't be guaranteed I think at this stage maybe just hardcoding the tab index to the keyword and location fields would be the way to go. Most important is that those fields have priority in focus when tab is pressed. Moving the index to environment variables feels like it'd clutter the environment variables for not much gain, and ideally the tab index would cover the input fields and result list items, which could expand to dozens of items, which I don't think would be wieldy for envvars. 

I'll update this PR with two hardcoded tabindex in the keyword and location inputs unless I hear otherwise.

**Comment by anselmbradford** [comment]
Continued development happening in https://github.com/codeforamerica/ohana-web-search/pull/749

**Pull request closed without merging**
