### PR TITLE
Fixes #496 - removes redundant floating header.

### LINKED ISSUE #496: Can floating header be implemented without rendering the same partial twice?
It seems strange to me that you would have to render the same content twice to use this feature. Is that a standard implementation? If not, it would be preferable to find an alternative solution for performance reasons.

### PR DESCRIPTION
**Pull request by anselmbradford**
- Fixes #496 - Uses text-overflow:ellipsis to truncate floating header
text so that header can be a fixed height, removing the need to have a
duplicate reference header. Truncating the text required reversing the
float direction of the left and right columns in the header and
updating the tests to reference the floating header instead of the
persistent header.

### CODE REVIEW

**Comment by anselmbradford** [comment]
Also fixes #243.

**Comment by anselmbradford** [comment]
@monfresh Ready for review and merge. Thx!

**Comment by anselmbradford** [comment]
Resize window when the floating header is displayed to see truncated location title.

**Comment by anselmbradford** [comment]
Appearance of truncated title at small screen size:

screen shot 2015-01-11 at 1 36 52 pm

**Comment by anselmbradford** [comment]
Also fixes https://github.com/codeforamerica/ohana-web-search/issues/502

**Comment by monfresh** [comment]
LGTM. :+1:

**Pull request merged**
