### PR TITLE
Updates google-api-client gem to 0.8.1.1

### PR DESCRIPTION
**Pull request by anselmbradford**
Updates google-api-client gem from 0.7.1 to 0.8.1.1

### CODE REVIEW

**Comment by monfresh** [comment]
Were you able to test that translation still works? If not, we shouldn't update the gem until we can test the keyword translation feature.

**Comment by anselmbradford** [comment]
It does work, however I found there's an error when the translation quota is reached because the controller logic doesn't handle an empty result set. We also need to add a little to the customization docs. I'll open issues...

**Comment by monfresh** [comment]
Do you have a working Google account that's not over quota that you were able to test this with?

**Comment by anselmbradford** [comment]
Yes

**Comment by anselmbradford** [comment]
Tested as follows:
- search for `food` and note SF Citadel Corps is returned.
- translate page to Spanish on homepage.
- search for `comida`, note no results.
- enable commented out lines in location_controller and added API key to application.yml.
- search for `comida` and note SF Citadel Corps is returned.

**Pull request merged**
