### PR TITLE
Updates haml-rails to 0.8.2

### PR DESCRIPTION
**Pull request by anselmbradford**
Updates haml-rails to 0.8.2 from 0.7.0.

### CODE REVIEW

**Comment by anselmbradford** [comment]
@monfresh Ready for review and merge. Thx! Adds version to gemfile since haml-rails is dependent on certain rails versions.

**Comment by monfresh** [comment]
Restricting versions in the Gemfile is only necessary if upgrading breaks the app or if it is incompatible with another gem we are using. Currently, haml-rails works with any version of Rails greater than 4.0.1, and we have 4.1.8, so there shouldn't be a need to restrict the version.

**Comment by anselmbradford** [comment]
Okay, I thought since it is tied to a particular Rails version they could just as easily be releasing a 0.9 or greater down the road that required Rails 4.2 or whatever and it could break, so I was interpreting that as a need for a version restriction; as we do with the `sass-rails`, `compass-rails`, and `requirejs-rails` gems.

**Comment by anselmbradford** [comment]
Rebased and pushed an edit w/o the version.

**Comment by monfresh** [comment]
The same could be said for any gem. Our version restrictions should not depend on what a gem maintainer might or might not do in the future. If there's a new version available, the process is to read the release notes, and if it turns out that it introduces new dependencies that are incompatible with our app, that would be the time to add a version restriction.

Also, note that `~> 0.8` will still allow 0.9 to be installed. If you want to restrict at the minor version, you need to add the patch version, such as `~> 0.8.0`.

**Comment by anselmbradford** [comment]
I thought the point of the version restriction was that someone installing the project for the first time wouldn't accidentally be getting a newer gem version than we intended. If a newer version comes out we'll only get the latest with `bundle update <gem>` (or equivalent), since we've already bootstrapped the project. But someone downloading the project and running `bundle` (well, `script/bootstrap) for the first time will get the latest version, which could be one that we've yet to test. Isn't that how it works?

**Comment by monfresh** [comment]
Not quite. When you run `bundle`, it installs the versions defined in Gemfile.lock. This ensures that everyone is using the same version. If you think about it, without Gemfile.lock, we would need to specify an exact version of every single gem in the Gemfile if we wanted to ensure everyone using the app was installing the same version of every gem.

**Comment by anselmbradford** [comment]
Haha, I just realized that and was going in to message when you posted. Got it.

**Pull request merged**
