### PR TITLE
Fixes #777 - adds logo template file

### LINKED ISSUE #777: Provide template logo source file
As a convenience, provide a template source file for https://github.com/codeforamerica/ohana-web-search/blob/master/app/assets/images/app_logo.png

This involves adjusting the logo slightly to one that can be created using a free font and also paves the way to use a logotype graphic for https://github.com/codeforamerica/ohana-web-search/issues/239

### PR DESCRIPTION
**Pull request by anselmbradford**
Fixes #777 - adds logo template file with a reference to a royalty-free
font, and updates the app_logo using that font, as well as the graphics
readme.

### CODE REVIEW

**Comment by anselmbradford** [comment]
Illustrator file looks like:

screen shot 2015-02-15 at 3 26 16 pm

**Comment by anselmbradford** [comment]
@monfresh I'm going to test whether I can save out a copy of this file as an SVG and can open/edit/export this in Inkscape to provide a free avenue for using these templates outside of Illustrator. I'll merge this soon after unless I hear otherwise.

**Comment by monfresh** [comment]
Sounds good to me. Thanks mang.

**Comment by anselmbradford** [comment]
AI and SVG files in Adobe Illustrator and Inkscape, respectively.

map-icons-template.ai:
screen shot 2015-02-16 at 4 44 30 pm

map-icons-template.svg:
screen shot 2015-02-16 at 4 45 50 pm

app_logo.ai
screen shot 2015-02-16 at 4 42 54 pm

app_logo.svg
screen shot 2015-02-16 at 4 45 11 pm

**Pull request merged**
